### ISSUE TITLE
The app crashes and exits on startup after calling Countly.init(), ios emulator, RN 0.62

### ISSUE THREAD

**Issue by Yasernova** [Countly/countly-sdk-react-native-bridge#10]
`
import Countly from 'countly-sdk-react-native-bridge';

import { REACT_APP_COUNTLY_URL, REACT_APP_COUNTLY_APP_KEY } from 'react-native-dotenv';

console.log({ REACT_APP_COUNTLY_URL, REACT_APP_COUNTLY_APP_KEY });

// initialize
var deviceId = null; // or use some string that identifies current app user
Countly.init(REACT_APP_COUNTLY_URL, REACT_APP_COUNTLY_APP_KEY, deviceId);

// configure other Countly parameters if needed
Countly.enableLogging();

// start session tracking
Countly.start();
`

**Comment by ArtursKadikis** [comment]
Hello, which sdk version are you using?
Move the enableLogging call before init and check what messages the ios log is showing.

**Comment by dawidvdh** [comment]
Experiencing the same issue, @Yasernova did you find a solution to this?

**Comment by ArtursKadikis** [comment]
Hello, the issue comes from passing "null" explicitly. It can be worked around by just providing the url and appKey, This issue is fixed in the upcomming release.

**Comment by cameroncharles** [comment]
For anyone else that winds up here looking for ios issues i had a similar issue but the "solution" was the opposite of the final post here, maybe because i'm on an older RN version

RN 0.60.x, countly 20.4.x ios app crashed with an obscure native message about attempting to run length on null, the stack trace included countly which led me here, i was running init() with only the url and key, no third param at all, supplying it with null fixed it up and got it going

**Comment by ijunaid** [comment]
@cameroncharles for iOS by supplying null in the third param will not fix the issue. In the current SDK release, the device Id param should contain a non-empty string. When device id is a non-empty string the SDK will store persistently and will be used in the next app start.
So in your case, you have already provided a non-empty string in init and now you are passing null in device Id and SDK is using the stored non-empty value due to which you are not getting an exception.

This issue is fixed and will be available in the next release.

**Comment by andreialecu** [comment]
@ArtursKadikis, @ijunaid: This crash still exists using the latest 20.4.9 version.

That release seems to be from October, but it was mentioned this was fixed in August. Was this fix released?
